### ISSUE TITLE
ssh into container immediately closes the connection

### ISSUE THREAD

**Issue by mpodber1971** [jeroenpeeters/docker-ssh#11]
i ran this command from the instance where docker resides:
sudo docker run -d -p 2222:22 \
  -v /var/run/docker.sock:/var/run/docker.sock \
  -e CONTAINER=matt -e AUTH_MECHANISM=noAuth \
  jeroenpeeters/docker-ssh

i run the ssh command to the instance: 
ssh -p 2222 -i <KEY_LOCATION> user@ipaddress 

and get the following dialogue before it closes the connection immediately

 ###############################################################
 ## Docker SSH ~ Because every container should be accessible ##
 ###############################################################
 ## container | matt                                          ##
 ###############################################################

Connection to XX.XXX.XX.XXX closed by remote host.
Connection to XX.XXX.XX.XXX closed.

**Comment by mpodber1971** [comment]
does the sshd service need to be running on the container?

**Comment by tikoflano** [comment]
Same problem here. The `docker logs` command shows the following error:

> [2016-06-03T17:50:58.310Z]  INFO: webserver/28 on 00e42964dbb5: Listening (host=::, port=8022)
> [2016-06-03T17:50:58.327Z]  INFO: sshServer/28 on 00e42964dbb5: Docker-SSH ~ Because every container should be accessible
> [2016-06-03T17:50:58.328Z]  INFO: sshServer/28 on 00e42964dbb5: Listening (host=0.0.0.0, port=22)
> [2016-06-03T17:50:59.110Z]  INFO: webserver/28 on 00e42964dbb5: New terminal session { terminalId: '2cfe75d4-1890-4e72-a95c-efe1f23e19fd' }
> [2016-06-03T17:50:59.116Z]  INFO: sessionHandler/28 on 00e42964dbb5: Opening shell (container=centos)
> /src/src/session-handler-factory.coffee:133
>                 return exec.start({
>                            ^
> 
> TypeError: Cannot read property 'start' of null
>   at Object.callback (/src/src/session-handler-factory.coffee:69:15)
>   at /src/node_modules/dockerode/lib/container.js:283:26
>   at [object Object].Modem.buildPayload (/src/node_modules/dockerode/node_modules/docker-modem/lib/modem.js:225:19)
>   at ClientRequest.<anonymous> (/src/node_modules/dockerode/node_modules/docker-modem/lib/modem.js:210:10)
>   at emitOne (events.js:77:13)
>   at ClientRequest.emit (events.js:169:7)
>   at Socket.socketErrorListener (_http_client.js:258:9)
>   at emitOne (events.js:77:13)
>   at Socket.emit (events.js:169:7)
>   at emitErrorNT (net.js:1256:8)
>   at nextTickCallbackWith2Args (node.js:441:9)
>   at process._tickCallback (node.js:355:17)
> 
> error: Forever detected script exited with code: 1
> error: Script restart attempt #1

**Comment by tikoflano** [comment]
Are you running Docker on Windows? If so check #7.

**Comment by alexmipego** [comment]
Had a similar issue today and it turned out to be a typo and permissions on the /var/run/docker.sock and in your case it could be permissions too. Try changing the volume flag to:

-v /var/run/docker.sock:/var/run/docker.sock:Z

That should setup SELinux permissions correctly if that happens to be the issue.

**Comment by mgomma** [comment]
I have the same issue on ubuntu the client and on the server and logs return:

```
/src/src/session-handler-factory.coffee:156
                  stream.on('data', function(data) {
                        ^

TypeError: Cannot read property 'on' of null
  at Object.callback (/src/src/session-handler-factory.coffee:79:19)
  at /src/node_modules/dockerode/lib/exec.js:39:10
  at Modem.buildPayload (/src/node_modules/docker-modem/lib/modem.js:225:19)
  at ClientRequest.<anonymous> (/src/node_modules/docker-modem/lib/modem.js:210:10)
  at emitOne (events.js:96:13)
  at ClientRequest.emit (events.js:188:7)
  at writeAfterEndNT (_http_outgoing.js:486:8)
  at _combinedTickCallback (internal/process/next_tick.js:77:11)
  at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by piotr-s-brainhub** [comment]
+1

Darwin mbp-user 16.3.0 Darwin Kernel Version 16.3.0: Thu Nov 17 20:23:58 PST 2016; root:xnu-3789.31.2~1/RELEASE_X86_64 x86_64

Docker version 1.13.0, build 49bf474

**Comment by Metachemix1** [comment]
@mgomma i had the same issue, building the dockerfile in this git repository again resolved the issue

Also i had to quote this with single quotes `FILTERS={\"name\":[\"^/my-container$\"]}`

The full command

`docker run -e 'FILTERS={\"name\":[\"^/my-container$\"]}' -e AUTH_MECHANISM=simpleAuth -e AUTH_USER=sshd -e AUTH_PASSWORD=1234 --name sshd -p 2222:22 --rm -v /var/run/docker.sock:/var/run/docker.sock docker-ssh`

Note during the build i encountered the following warnings:
```

> dtrace-provider@0.6.0 install /usr/src/app/node_modules/dtrace-provider
> node scripts/install.js

npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.2 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

added 209 packages in 5.672s
npm WARN using --force I sure hope you know what you are doing.
```

This works on Docker For Windows

```Client:
 Version:      18.05.0-ce-rc1
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   33f00ce
 Built:        Thu Apr 26 00:57:53 2018
 OS/Arch:      windows/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.05.0-ce-rc1
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.10.1
  Git commit:   33f00ce
  Built:        Thu Apr 26 01:06:49 2018
  OS/Arch:      linux/amd64
  Experimental: true```

**Comment by chungyan5** [comment]
hi all, 
i got this kind of error too. 

I forget that to installed the "bash" into the objective container, eg. in alpine image, "apk add bash".
