### ISSUE TITLE
 Forever detected script exited with code: 1 ?

### ISSUE THREAD

**Issue by khangprolxag** [jeroenpeeters/docker-ssh#19]
hi. can you help me this?
i start the docker-ssh and i found no problem
but when i try to connect ssh
and it return [2016-11-16T16:29:44.752Z]  INFO: sshServer/44 on 711da3200ebb: Listening (host=0.0.0.0, port=22)
[2016-11-16T16:29:45.108Z]  INFO: sshServer/44 on 711da3200ebb: Client connected (clientIp=172.19.0.1)
[2016-11-16T16:29:45.175Z] ERROR: noAuthHandler/44 on 711da3200ebb: NoAuthentication handler is handling the authentication! This is INSECURE!
[2016-11-16T16:29:45.258Z]  INFO: sessionHandler/44 on 711da3200ebb: Opening shell (container=test-ssh)
[2016-11-16T16:29:45.400Z]  INFO: sessionHandler/44 on 711da3200ebb: Terminal exited (container=test-ssh)
[2016-11-16T16:29:45.405Z]  INFO: sessionHandler/44 on 711da3200ebb: Channel exited (container=test-ssh)
[2016-11-16T16:29:45.407Z]  INFO: sshServer/44 on 711da3200ebb: Client disconnected (clientIp=172.19.0.1)
/src/src/session-handler-factory.coffee:156
                  stream.on('data', function(data) {
                        ^

TypeError: Cannot read property 'on' of null
  at Object.callback (/src/src/session-handler-factory.coffee:79:19)
  at /src/node_modules/dockerode/lib/exec.js:39:10
  at Modem.buildPayload (/src/node_modules/docker-modem/lib/modem.js:225:19)
  at ClientRequest.<anonymous> (/src/node_modules/docker-modem/lib/modem.js:210:10)
  at emitOne (events.js:96:13)
  at ClientRequest.emit (events.js:188:7)
  at writeAfterEndNT (_http_outgoing.js:499:8)
  at _combinedTickCallback (internal/process/next_tick.js:77:11)
  at process._tickCallback (internal/process/next_tick.js:98:9)

error: Forever detected script exited with code: 1
error: Script restart attempt #2
AND DISCONNECT to the terminal
please help me

**Comment by khangprolxag** [comment]
this is my compose file  
ssh:
    image: jeroenpeeters/docker-ssh
    container_name: test-ssh
    mem_limit: 5000m
    ports:
      - "2222:22"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - HTTP_ENABLED=true
      - AUTH_MECHANISM=noAuth

**Comment by josejulio** [comment]
I think you need to set your container name:

e.g.
```
environment:
- HTTP_ENABLED=true
- AUTH_MECHANISM=noAuth
- FILTERS={"name":["^/your_container_name$$"]}
```
