### ISSUE TITLE
Type error: resizeTerm is not a function

### ISSUE THREAD

**Issue by wishforgood** [jeroenpeeters/docker-ssh#50]
I'm trying to connect to my docker container through x2go remote desktop. So I use docker-ssh as a ssh server to help ssh into the container. However, after type into username and password, I got the following error:  
![image](https://user-images.githubusercontent.com/9963412/44902881-b2d95d00-ad3d-11e8-894e-ac96db6160f6.png)

Because it's reported by docker-ssh, I guess it may be some bug.

**Comment by fnagel** [comment]
Same issue here. Using Docker Toolbox for Windows.

````
ssh ssh@192.168.99.100 -p 2222
ssh@192.168.99.100's password:

 ###############################################################
 ## Docker SSH ~ Because every container should be accessible ##
 ###############################################################
 ## container | /typo3.webserver.dev.typo3-9.docker           ##
 ###############################################################

Connection to 192.168.99.100 closed by remote host.
Connection to 192.168.99.100 closed.
````

Error:
````
[2019-01-07T12:12:23.079Z]  INFO: webserver/43 on e086c296f18f: Listening (host=::, port=8022)
[2019-01-07T12:12:23.080Z]  INFO: sshServer/43 on e086c296f18f: Docker-SSH ~ Because every container should be accessible
[2019-01-07T12:12:23.080Z]  INFO: sshServer/43 on e086c296f18f: Listening (host=0.0.0.0, port=22)
[2019-01-07T12:23:17.781Z]  INFO: sshServer/43 on e086c296f18f: Client connected (clientIp=192.168.99.1)
[2019-01-07T12:23:20.047Z]  INFO: simpleAuth/43 on e086c296f18f: Authentication succeeded (user=ssh)
[2019-01-07T12:23:20.142Z]  INFO: sessionHandler/43 on e086c296f18f: Opening shell (container=/typo3.webserver.dev.typo3-9.docker)
[2019-01-07T12:23:20.153Z]  INFO: sessionHandler/43 on e086c296f18f: window-change { cols: 211, rows: 50, width: 640, height: 480 } (container=/typo3.webserver.dev.typo3-9.docker)
/usr/src/app/src/session-handler-factory.coffee:227
                return resizeTerm(info);
                       ^
2019-01-07T12:23:20.404636406Z 
TypeError: resizeTerm is not a function
  at Session.<anonymous> (/usr/src/app/src/session-handler-factory.coffee:128:11)
  at emitThree (events.js:116:13)
  at Session.emit (events.js:194:7)
  at SSH2Stream.onREQUEST (/usr/src/app/node_modules/ssh2/lib/server.js:598:16)
  at emitOne (events.js:101:20)
  at SSH2Stream.emit (events.js:188:7)
  at parse_CHANNEL_REQUEST (/usr/src/app/node_modules/ssh2-streams/lib/ssh.js:4356:8)
  at parsePacket (/usr/src/app/node_modules/ssh2-streams/lib/ssh.js:3727:12)
  at SSH2Stream._transform (/usr/src/app/node_modules/ssh2-streams/lib/ssh.js:551:13)
  at SSH2Stream.Transform._read (_stream_transform.js:167:10)
  at SSH2Stream._read (/usr/src/app/node_modules/ssh2-streams/lib/ssh.js:212:15)
  at SSH2Stream.Transform._write (_stream_transform.js:155:12)
  at doWrite (_stream_writable.js:331:12)
  at writeOrBuffer (_stream_writable.js:317:5)
  at SSH2Stream.Writable.write (_stream_writable.js:243:11)
  at Socket.ondata (_stream_readable.js:555:20)
  at emitOne (events.js:96:13)
  at Socket.emit (events.js:188:7)
  at readableAddChunk (_stream_readable.js:176:18)
  at Socket.Readable.push (_stream_readable.js:134:10)
  at TCP.onread (net.js:547:20)
2019-01-07T12:23:20.404871194Z 
error: Forever detected script exited with code: 1
error: Script restart attempt #3
[2019-01-07T12:23:21.589Z]  INFO: sshServer/49 on e086c296f18f: Docker filter
    filter: {
      "name": [
        "^/typo3.webserver.dev.typo3-9.docker$"
      ]
    }
[2019-01-07T12:23:21.618Z]  INFO: webserver/49 on e086c296f18f: Listening (host=::, port=8022)
[2019-01-07T12:23:21.619Z]  INFO: sshServer/49 on e086c296f18f: Docker-SSH ~ Because every container should be accessible
[2019-01-07T12:23:21.620Z]  INFO: sshServer/49 on e086c296f18f: Listening (host=0.0.0.0, port=22)
````

**Comment by belqit** [comment]
same issue here
