### ISSUE TITLE
VSCode and Remote-SSH Extension

### ISSUE THREAD

**Issue by mwisconsin** [jeroenpeeters/docker-ssh#58]
Using docker-ssh, attempting to connect to the container will return the following output:

```
[14:47:20.125] Log Level: 1
[14:47:20.127] remote-ssh@0.76.1
[14:47:20.127] win32 x64
[14:47:20.145] SSH Resolver called for "ssh-remote+sanitized", attempt 1
[14:47:20.146] "remote.SSH.useLocalServer": false
[14:47:20.146] "remote.SSH.showLoginTerminal": true
[14:47:20.146] "remote.SSH.remotePlatform": {"stage.sanitized.com":"linux","sanitized":"linux","sanitized":"linux"}
[14:47:20.146] "remote.SSH.path": undefined
[14:47:20.147] "remote.SSH.configFile": undefined
[14:47:20.147] "remote.SSH.useFlock": true
[14:47:20.147] "remote.SSH.lockfilesInTmp": false
[14:47:20.147] "remote.SSH.localServerDownload": always
[14:47:20.147] "remote.SSH.remoteServerListenOnSocket": false
[14:47:20.147] "remote.SSH.showLoginTerminal": true
[14:47:20.148] "remote.SSH.defaultExtensions": []
[14:47:20.148] "remote.SSH.loglevel": 1
[14:47:20.148] "remote.SSH.enableDynamicForwarding": true
[14:47:20.148] "remote.SSH.enableRemoteCommand": false
[14:47:20.148] "remote.SSH.serverPickPortsFromRange": {}
[14:47:20.148] "remote.SSH.serverInstallPath": {}
[14:47:20.181] SSH Resolver called for host: sanitized
[14:47:20.181] Setting up SSH remote "sanitized"
[14:47:20.213] Using commit id "c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1" and quality "stable" for server
[14:47:20.225] Install and start server if needed
[14:47:20.231] Checking ssh with "ssh -V"
[14:47:20.569] > OpenSSH_for_
[14:47:20.570] > Windows_8.1p1, LibreSSL 3.0.2

[14:47:20.576] Running script with connection command: ssh -T -D 54041 sanitized bash
[14:47:20.579] Terminal shell path: C:\WINDOWS\System32\cmd.exe
[14:47:21.118] "install" terminal received data: "[2J[m[H]0;C:\WINDOWS\System32\cmd.exe[?25h"
[14:47:21.119] Got some output, clearing connection timeout
[14:47:21.141] "install" terminal received data: "[25l[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K[H[?25h"
[14:47:23.095] "install" terminal command done
[14:47:23.096] Install terminal quit with output: ]0;C:\WINDOWS\System32\cmd.exe
[14:47:23.096] Received install output: ]0;C:\WINDOWS\System32\cmd.exe
[14:47:23.096] Stopped parsing output early. Remaining text: ]0;C:\WINDOWS\System32\cmd.exe
[14:47:23.096] Failed to parse remote port from server output
[14:47:23.097] Resolver error: Error: 
	at Function.Create (c:\Users\sanitized\.vscode\extensions\ms-vscode-remote.remote-ssh-0.76.1\out\extension.js:1:586041)
	at Object.t.handleInstallOutput (c:\Users\sanitized\.vscode\extensions\ms-vscode-remote.remote-ssh-0.76.1\out\extension.js:1:584693)
	at Object.t.tryInstall (c:\Users\sanitized\.vscode\extensions\ms-vscode-remote.remote-ssh-0.76.1\out\extension.js:1:681846)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async c:\Users\sanitized\.vscode\extensions\ms-vscode-remote.remote-ssh-0.76.1\out\extension.js:1:644486
	at async Object.t.withShowDetailsEvent (c:\Users\sanitized\.vscode\extensions\ms-vscode-remote.remote-ssh-0.76.1\out\extension.js:1:647831)
	at async Object.t.resolve (c:\Users\sanitized\.vscode\extensions\ms-vscode-remote.remote-ssh-0.76.1\out\extension.js:1:645565)
	at async c:\Users\sanitized\.vscode\extensions\ms-vscode-remote.remote-ssh-0.76.1\out\extension.js:1:722872
[14:47:23.100] TELEMETRY: {"eventName":"resolver","properties":{"osReleaseId":"","arch":"","askedPw":"0","askedPassphrase":"0","asked2fa":"0","askedHostKey":"0","remoteInConfigFile":"1","gotUnrecognizedPrompt":"0","dynamicForwarding":"1","localServer":"0","didLocalDownload":"0","installUnpackCode":"0","outcome":"failure","reason":"UnparsableOutput","exitCodeLabel":""},"measures":{"resolveAttempts":1,"retries":1,"timing.totalResolveTime":2952,"timing.preSshTime":434,"timing.scriptTime":2518}}
[14:47:23.104] ------
```

The error occurs here:
```
[14:47:23.096] Failed to parse remote port from server output
```

Is there a configuration option with the setup of docker-ssh that could resolve this? Or is there an expectation from VSCode's attempt to install the remote SSH VS Code server settings that make this pairing of products unresolvable?

**Comment by protubero** [comment]
Same problem here.
